FRAMEWORK_NAME=$1
FRAMEWORK_DIR=$2
INTERFACE=$3
OUTPUT_DIR=$4
SOURCE_PATH="$FRAMEWORK_DIR/$FRAMEWORK_NAME.framework/Modules/$FRAMEWORK_NAME.swiftmodule/$INTERFACE.swiftinterface"
cp $SOURCE_PATH "$OUTPUT_DIR/${FRAMEWORK_NAME}_swift_api.txt"
